[2024-11-02T06:30:59.476+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transaction_facts_generator.generate_txn_fact_data scheduled__2024-08-25T00:00:00+00:00 [queued]>
[2024-11-02T06:30:59.494+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transaction_facts_generator.generate_txn_fact_data scheduled__2024-08-25T00:00:00+00:00 [queued]>
[2024-11-02T06:30:59.495+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-11-02T06:30:59.539+0000] {taskinstance.py:1380} INFO - Executing <Task(KafkaProducerOperator): generate_txn_fact_data> on 2024-08-25 00:00:00+00:00
[2024-11-02T06:30:59.548+0000] {standard_task_runner.py:57} INFO - Started process 4299 to run task
[2024-11-02T06:30:59.554+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'transaction_facts_generator', 'generate_txn_fact_data', 'scheduled__2024-08-25T00:00:00+00:00', '--job-id', '1125', '--raw', '--subdir', 'DAGS_FOLDER/transaction_facts_generator.py', '--cfg-path', '/tmp/tmp9zt0bu1k']
[2024-11-02T06:30:59.563+0000] {standard_task_runner.py:85} INFO - Job 1125: Subtask generate_txn_fact_data
[2024-11-02T06:30:59.655+0000] {task_command.py:415} INFO - Running <TaskInstance: transaction_facts_generator.generate_txn_fact_data scheduled__2024-08-25T00:00:00+00:00 [running]> on host 5e812a6a7c02
[2024-11-02T06:30:59.776+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='minhtranquang' AIRFLOW_CTX_DAG_ID='transaction_facts_generator' AIRFLOW_CTX_TASK_ID='generate_txn_fact_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-25T00:00:00+00:00'
[2024-11-02T06:30:59.781+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka_broker:9092 <connecting> [IPv4 ('172.20.0.4', 9092)]>: connecting to kafka_broker:9092 [('172.20.0.4', 9092) IPv4]
[2024-11-02T06:30:59.782+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-11-02T06:30:59.784+0000] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka_broker:9092 <connecting> [IPv4 ('172.20.0.4', 9092)]>: Connection complete.
[2024-11-02T06:30:59.895+0000] {conn.py:1267} INFO - Broker version identified as 2.5.0
[2024-11-02T06:30:59.896+0000] {conn.py:1268} INFO - Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2024-11-02T06:30:59.902+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/kafka_operator.py", line 58, in execute
    transaction = self.generate_transaction_data(row_num)
  File "/opt/airflow/plugins/kafka_operator.py", line 31, in generate_transaction_data
    transaction_type = random.choice(transaction_types)
AttributeError: module 'random' has no attribute 'choic'
[2024-11-02T06:30:59.929+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=transaction_facts_generator, task_id=generate_txn_fact_data, execution_date=20240825T000000, start_date=20241102T063059, end_date=20241102T063059
[2024-11-02T06:30:59.964+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1125 for task generate_txn_fact_data (module 'random' has no attribute 'choic'; 4299)
[2024-11-02T06:31:00.011+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-02T06:31:00.068+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
