[2024-11-02T14:09:39.197+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: table_dag.submit_tables manual__2024-11-02T14:09:36.239921+00:00 [queued]>
[2024-11-02T14:09:39.207+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: table_dag.submit_tables manual__2024-11-02T14:09:36.239921+00:00 [queued]>
[2024-11-02T14:09:39.208+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-11-02T14:09:39.224+0000] {taskinstance.py:1380} INFO - Executing <Task(PinotTableSubmitOperator): submit_tables> on 2024-11-02 14:09:36.239921+00:00
[2024-11-02T14:09:39.229+0000] {standard_task_runner.py:57} INFO - Started process 1228 to run task
[2024-11-02T14:09:39.231+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'table_dag', 'submit_tables', 'manual__2024-11-02T14:09:36.239921+00:00', '--job-id', '1797', '--raw', '--subdir', 'DAGS_FOLDER/table_dag.py', '--cfg-path', '/tmp/tmpp_obtt_q']
[2024-11-02T14:09:39.234+0000] {standard_task_runner.py:85} INFO - Job 1797: Subtask submit_tables
[2024-11-02T14:09:39.278+0000] {task_command.py:415} INFO - Running <TaskInstance: table_dag.submit_tables manual__2024-11-02T14:09:36.239921+00:00 [running]> on host 5e812a6a7c02
[2024-11-02T14:09:39.360+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='minhtranquang' AIRFLOW_CTX_DAG_ID='table_dag' AIRFLOW_CTX_TASK_ID='submit_tables' AIRFLOW_CTX_EXECUTION_DATE='2024-11-02T14:09:36.239921+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-02T14:09:36.239921+00:00'
[2024-11-02T14:09:39.509+0000] {pinot_table_operator.py:28} INFO - Table successfully submitted to Apache Pinot! /opt/***/dags/tables/account_dim.json
[2024-11-02T14:09:39.529+0000] {pinot_table_operator.py:30} ERROR - Failed to submit table: 400 - {"code":400,"error":"Column Name branch_dim defined in Sorted Column Config must be a valid column defined in the schema"}
[2024-11-02T14:09:39.531+0000] {pinot_table_operator.py:33} ERROR - An error occured: Table submission failed with status code 400
[2024-11-02T14:09:39.552+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=table_dag, task_id=submit_tables, execution_date=20241102T140936, start_date=20241102T140939, end_date=20241102T140939
[2024-11-02T14:09:39.606+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-11-02T14:09:39.649+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
